<?php

// Implements hook_menu();

function formula_menu_menu() {
  $items = array();
    $items['formula'] = array(
      'title' => "Formula 1 Menu",
      'page callback' => 'formula_1_menu',
      'access arguements' => array('access content')
    );
  return $items;
}


function formula_menu_basic() {
  $content = array();
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => "<p>Here's an example how to implement some text into the Demo Page for Formula 1 learning.</p>",
  );
  return $content;
}

// Permission administration for Formula 1 Module

function formula_menu_permission() {
  return array(
    'administer formula 1 menu module' => array(
      'title' => t('Administer Formula 1 menu module'),
      'description' => t('Perform adminisitration for the Formula 1 Module.'),
    ),
  );
}

function formula_node_view($node, $view_mode, $langcode) {
  $node->content['formula_field'] = array(
    '#type' => 'markup',
    '#markup' => '<p>'.t('Formula 1 Constructors.').'</p>',
    '#weight' => -10,
  );
  $node->content['formula_list'] = array(
     '#items' => array('Ferrari', 'Mercedes', 'Lotus', 'Renault', 'Red Bull', 'McLaren', 'Haas', 'Sauber'),
     '#theme' => 'item_list',
     '#weight' => -9,
  );
  krumo($node);
}

// Implements the new hook_permission
