<?php

// Implements hook_menu();

function formula_menu_menu() {
  $items = array();
    $items['formula'] = array(
      'title' => "Formula 1 Menu",
      'page callback' => 'formula_1_menu',
      'access arguements' => array('access content')
    );
  return $items;
}


function formula_menu_basic() {
  $content = array();
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => "<p>Here's an example how to implement some text into the Demo Page for Formula 1 learning.</p>",
  );
  return $content;
}

// Permission administration for Formula 1 Module

function formula_menu_permission() {
  return array(
    'administer formula 1 menu module' => array(
      'title' => t('Administer Formula 1 menu module'),
      'description' => t('Perform adminisitration for the Formula 1 Module.'),
    ),
  );
}

function formula_node_view($node, $view_mode, $langcode) {
  $node->content['formula_field'] = array(
    '#type' => 'markup',
    '#markup' => '<p>'.t('Formula 1 Constructors.').'</p>',
    '#weight' => -10,
  );
  $node->content['formula_list'] = array(
     '#items' => array('Ferrari', 'Mercedes', 'Lotus', 'Renault', 'Red Bull', 'McLaren', 'Haas', 'Sauber'),
     '#theme' => 'item_list',
     '#weight' => -9,
  );
  krumo($node);
}

// Implements the new hook_permission

// be sure to edit this code before activating 
$variables = array(
  'path' => 'https://upload.wikimedia.org/wikipedia/commons/d/de/Kimi_Raikkonen_2007_Malaysia.jpg',
  'alt' => t('Kimi Raikkonen behind the wheel of the Ferrari F2007, something that was truly magical.'),
  'title' => t('Kimi Raikkonen en route to winning the 2007 Malaysia GP.'),
);
$content['themed_data'] = array(
  '#type' => 'markup',
  '#markup' => theme('image', $variables),
  '#prefix' => '<div class="menu-magic-kimi-raikkonen-image">',
  '#suffix' => '</div>',
  '#attached' => array(
    'css' => array(
      drupal_get_path('module', 'menu_magic') . '/menu_magic.css',
    ),
  ),
);

$content['renderable_element'] = array(
  '#theme' => 'item_list',
  '#title' => t('Kimi Raikkonen 2007 Season Highlights'),
  '#items' => array(
    t("2007 World Champion"),
    t("6 Race Victories"),
    t("6 Fastest Laps"),
    t("3 Pole Positions"),
    t('The current time is %time.', array('%time' => date('r'))),
  ),
  '#cache' => array(
    'keys' => array('menu_magic', 'renderable_element'), // menu_magic:renderable_element
    'bin' => 'cache',
    'expire' => time() + 30,
    'granularity' => DRUPAL_CACHE_PER_PAGE,
  ),
);

return $content;
}
