<?php


/**
 * Implements hook_menu().
 */
function menu_magic_menu() {
  $items = array();

  $items['magic'] = array(
    'title' => 'A little magic',
    'page callback' => 'menu_magic_basic',
    'access arguments' => array('access content'),
  );

  $items['magic/%'] = array(
    'title' => 'Even more magical',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.extra.inc',
  );

  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'Magical magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK,
  );

  // node_load(%)
  $items['node/%node/magic'] = array(
    'title' => 'Magic',
    'description' => 'Do amazing and magical things',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

// content render function

function menu_magic_basic() {
  $content = array();
  // This is some very simple page element. It will appear on the page,
  // but other modules can't customize it and the themes can't override it's markup.

  // any time you see an render array without a # or hash, that is considered an element.
  //
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => "Here's an example of some text to add in to the demo page!",
    '#prefix' => "<p>",
    '#suffix' -> '</p>'
  );
  return $content;
}

// Permission administration for magic module

function menu_magic_permission() {
  return array(
    'administer menu magic module' => array(
      'title' => t("Administer menu magic module"),
      'description' => t('Perform administration for the Menu Magic Module.'),
    ),
  );
}
